version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fonseca_noah_coding_assignment12  # Set the container name here
    ports:
      - "8083:8083"  # Expose the app on port 8083
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
